min-api:
  base_url: 'https://min-api.cryptocompare.com/data/'
  news: 
    latest_news: 'v2/news/?lang=EN'
  exchange:
    full: 'top/exchanges/full'
    top: 'top/exchanges'
  historical_data:
    histominute: 'histominute'
    histohour: 'histohour'
deribit-api:
  base_url: 'https://www.deribit.com'
  order-book: '/api/v1/public/getorderbook'
kraken-api:
  base_url: 'https://api.kraken.com'
  order-book: '/0/public/Depth'
  ohlc: '/0/public/OHLC'
okcoin-api:
  base_url: 'https://www.okcoin.com'
  order-book: '/api/v1/depth.do'