min-api:
  base_url: 'https://min-api.cryptocompare.com/data/'
  news: 
    latest_news: 'v2/news/?lang=EN'
  exchange:
    full: 'top/exchanges/full'
    top: 'top/exchanges'
  historical_data:
    histominute: 'histominute'
    histohour: 'histohour'